version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: projecta
      MYSQL_DATABASE: backend
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      mynetwork:

  backend:
    container_name: backend
    image : 9907daniel/project_atogato-backend:latest
    ports:
      - "7072:7072"
    depends_on:
      - mysqldb
    networks:
      - mynetwork
    restart: on-failure

  frontend:
    container_name: frontend
    image: 9907daniel/project_atogato-frontend:latest
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysqldb_data:
