version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: projecta
      MYSQL_DATABASE: backend
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=deployment
    image : 9907daniel/project_atogato-backend:latest
    ports:
      - "127.0.0.1:7072:7072"
    depends_on:
      - mysqldb
    networks:
      - mynetwork
    restart: on-failure

volumes:
  mysqldb_data:
