name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches: [ "develop" ]

  pull_request:
    branches: [ "main" , "develop", "backend" ]
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (BE)
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          dockerfile: ./backend/Dockerfile
          tags: 9907daniel/project_atogato-backend:latest

      - name: Build and push Docker image (FE)
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          dockerfile: ./frontend/Dockerfile
          tags: 9907daniel/project_atogato-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Copy docker-compose file to remote server
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key.pem docker-compose.yml ubuntu@43.202.127.245:~
      - name: Deploy Docker Compose services
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.125.101.0   <<EOF
          sudo docker rm frontend backend -f
          sudo docker-compose pull
          sudo docker-compose down
          sudo docker-compose up -d
          EOF

